const DO_NOT_EDIT_COMMENT = `* This file is generated by a tool. Do not edit directly.\n`;
const GENERATED_BY_COMMENT = `* Generated by openapi-angular-generator.\n`;

const HEADER = `/**\n${DO_NOT_EDIT_COMMENT}${GENERATED_BY_COMMENT}*/\n\n`;

export const TYPE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const MAIN_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const PROVIDER_GENERATOR_HEADER_COMMENT = HEADER;
export const UTILITY_GENERATOR_HEADER_COMMENT = HEADER;
