// src/core/constants.ts
const DO_NOT_EDIT_COMMENT = `* This file is generated by a tool. Do not edit directly.\n`;
const GENERATED_BY_COMMENT = `* Generated by openapi-angular-generator.\n`;

const HEADER = `/**\n${DO_NOT_EDIT_COMMENT}${GENERATED_BY_COMMENT}*/\n\n`;

export const TYPE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const MAIN_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const PROVIDER_GENERATOR_HEADER_COMMENT = HEADER;
export const UTILITY_GENERATOR_HEADER_COMMENT = HEADER;

export const OAS_3_1_DIALECT = 'https://spec.openapis.org/oas/3.1/dialect/base';
export const JSON_SCHEMA_2020_12_DIALECT = 'https://json-schema.org/draft/2020-12/schema';
