const DO_NOT_EDIT_COMMENT = `* This file is generated by a tool. Do not edit directly.\n`;
const GENERATED_BY_COMMENT = `* Generated by openapi-angular-generator.\n`;

const HEADER = `/**\n${DO_NOT_EDIT_COMMENT}${GENERATED_BY_COMMENT}*/\n\n`;

export const TYPE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_GENERATOR_HEADER_COMMENT = HEADER;
export const SERVICE_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const MAIN_INDEX_GENERATOR_HEADER_COMMENT = HEADER;
export const PROVIDER_GENERATOR_HEADER_COMMENT = HEADER;
export const UTILITY_GENERATOR_HEADER_COMMENT = HEADER;

/**
 * The standard JSON Schema dialect identifier used by OpenAPI 3.1.
 * @see https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schema-vocabulary
 */
export const OAS_3_1_DIALECT = 'https://spec.openapis.org/oas/3.1/dialect/base';

/**
 * The standard JSON Schema dialect identifier for JSON Schema 2020-12, which OAS 3.1 is based on.
 */
export const JSON_SCHEMA_2020_12_DIALECT = 'https://json-schema.org/draft/2020-12/schema';
