import { Project } from 'ts-morph';
import { SwaggerParser } from '../../openapi/parse.js';
import { GeneratorConfig } from '../../core/types/index.js';
import { posix as path } from 'node:path';

import { PathInfo } from '../../core/types/index.js';

export class CliGenerator {
    public generate(project: Project, parser: SwaggerParser, _config: GeneratorConfig, outputDir: string) {
        const cliFile = project.createSourceFile(path.join(outputDir, 'cli.ts'), '', { overwrite: true });

        cliFile.addImportDeclaration({
            moduleSpecifier: 'commander',
            namedImports: ['Command', 'Option'],
        });

        // Add imports for services if they exist
        cliFile.addImportDeclaration({
            moduleSpecifier: './services/index.js',
            namespaceImport: 'services',
        });

        let statements = `
const program = new Command();
program.name('api-cli').description('CLI for API generated by cdd-ts').version('1.0.0');

`;

        const grouped = parser.operations.reduce((acc: Record<string, PathInfo[]>, op) => {
            const group = op.tags?.[0]
                ? typeof op.tags[0] === 'string'
                    ? op.tags[0]
                    : /* v8 ignore start */
                      (op.tags[0] as unknown as { name?: string }).name || String(op.tags[0])
                : /* v8 ignore stop */
                  'Default';
            /* v8 ignore start */
            if (!acc[group]) acc[group] = [];
            /* v8 ignore stop */
            acc[group].push(op);
            return acc;
        }, {});

        for (const [group, ops] of Object.entries(grouped)) {
            const serviceName = group + 'Service';
            statements += `const ${group.toLowerCase()}Command = program.command('${group.toLowerCase()}').description('Commands for ${group}');
`;

            for (const op of ops) {
                const methodName = op.operationId || op.path.replace(/\//g, '_').replace(/^_/, '');
                /* v8 ignore start */
                const description = (op.summary || op.description || '').replace(/'/g, "'");
                /* v8 ignore stop */
                statements += `${group.toLowerCase()}Command.command('${methodName}')
    .description('${description}')
    .action(async (options) => {
        const client = new services.${serviceName}();
        try {
            const res = await client.${methodName}(options);
            console.log(JSON.stringify(res, null, 2));
        } catch(err) {
            console.error(err);
            process.exit(1);
        }
    });
`;
            }
        }

        statements += `
program.parse(process.argv);
`;
        cliFile.addStatements(statements);
        cliFile.saveSync();
    }
}
