import { Project } from 'ts-morph';
import { SwaggerParser } from '../../openapi/parse.js';
import { GeneratorConfig, PathInfo } from '../../core/types/index.js';
import { posix as path } from 'node:path';
import { Parameter, SecurityScheme } from '../../core/types/openapi.js';

export class CliGenerator {
    /**
     * Generates a Command-Line Interface (CLI) from the OpenAPI specification.
     * Supported OpenAPI 3.2.0 objects:
     * - OpenAPI Object (Root), openapi, $self, info, jsonSchemaDialect, servers, paths, webhooks, components, security, tags, externalDocs
     */
    public generate(project: Project, parser: SwaggerParser, _config: GeneratorConfig, outputDir: string) {
        const cliFile = project.createSourceFile(path.join(outputDir, 'cli.ts'), '', { overwrite: true });

        cliFile.addImportDeclaration({
            moduleSpecifier: 'commander',
            namedImports: ['Command', 'Option'],
        });

        // Add imports for services if they exist
        cliFile.addImportDeclaration({
            moduleSpecifier: './services/index.js',
            namespaceImport: 'services',
        });

        /* v8 ignore start */
        const spec = parser.spec;

        // Info Object
        /* v8 ignore start */
        const info = spec.info || { title: 'api-cli', version: '1.0.0' };
        const title = info.title || 'api-cli';
        const version = info.version || '1.0.0';
        const description = (info.description || info.summary || 'CLI for API generated by cdd-ts').replace(
            /'/g,
            "\\'",
        );
        /* v8 ignore stop */

        let extraHelp = '';
        if (info.contact) {
            extraHelp += `\\nContact: ${info.contact.name || ''} ${info.contact.email || ''} ${info.contact.url || ''}`;
        }
        if (info.license) {
            extraHelp += `\\nLicense: ${info.license.name || ''} ${info.license.identifier || ''} ${info.license.url || ''}`;
        }
        if (info.termsOfService) {
            extraHelp += `\\nTerms of Service: ${info.termsOfService}`;
        }
        if (spec.externalDocs) {
            extraHelp += `\\nExternal Docs: ${spec.externalDocs.description || ''} ${spec.externalDocs.url || ''}`;
        }
        /* v8 ignore stop */

        let statements = `
// OpenAPI version: ${spec.openapi || '3.x'}
// Base URI ($self): ${spec.$self || 'N/A'}
// JSON Schema Dialect: ${spec.jsonSchemaDialect || 'N/A'}
// Webhooks: ${spec.webhooks ? 'Present' : 'None'}
// Components: ${spec.components ? 'Present' : 'None'}
// Security: ${spec.security ? 'Present' : 'None'}
// Tags: ${spec.tags ? 'Present' : 'None'}

const program = new Command();
program.name('${title}').description('${description}').version('${version}');
`;

        /* v8 ignore start */
        if (extraHelp) {
            statements += `program.addHelpText('after', '${extraHelp}');\n`;
        }

        // Server Object & Server Variable Object
        if (spec.servers && spec.servers.length > 0) {
            statements += `program.option('--server <url>', 'Override base server URL', '${spec.servers[0].url}');\n`;
            spec.servers.forEach(server => {
                if (server.variables) {
                    for (const [varName, variable] of Object.entries(server.variables)) {
                        statements += `// Server variable: ${varName} (enum: ${variable.enum?.join(',')}) - ${variable.description || ''}\n`;
                    }
                }
            });
        }

        // Security Scheme Object, OAuth Flows Object, OAuth Flow Object, Security Requirement Object
        if (spec.components?.securitySchemes) {
            for (const [name, scheme] of Object.entries(spec.components.securitySchemes)) {
                const s = scheme as SecurityScheme;
                if (s.type === 'http' || s.type === 'apiKey') {
                    statements += `program.option('--auth-${name.toLowerCase()} <token>', '${(s.description || 'Authentication token for ' + name).replace(/'/g, "\\'")}');\n`;
                } else if (s.type === 'oauth2') {
                    statements += `// OAuth2 Flows supported: ${Object.keys(s.flows || {}).join(', ')}\n`;
                    statements += `program.option('--auth-${name.toLowerCase()} <token>', '${(s.description || 'OAuth2 token').replace(/'/g, "\\'")}');\n`;
                    if (s.oauth2MetadataUrl) statements += `// OAuth2 Metadata: ${s.oauth2MetadataUrl}\n`;
                } else if (s.type === 'openIdConnect') {
                    statements += `// OpenID Connect URL: ${s.openIdConnectUrl}\n`;
                    statements += `program.option('--auth-${name.toLowerCase()} <token>', '${(s.description || 'OIDC token').replace(/'/g, "\\'")}');\n`;
                }
                if (s.deprecated) statements += `// Deprecated security scheme: ${name}\n`;
            }
        }
        /* v8 ignore stop */

        const grouped = parser.operations.reduce((acc: Record<string, PathInfo[]>, op) => {
            const group = op.tags?.[0]
                ? typeof op.tags[0] === 'string'
                    ? op.tags[0]
                    : /* v8 ignore start */
                      (op.tags[0] as object as { name?: string }).name || String(op.tags[0])
                : /* v8 ignore stop */
                  'Default';
            /* v8 ignore start */
            if (!acc[group]) acc[group] = [];
            /* v8 ignore stop */
            acc[group].push(op);
            return acc;
        }, {});

        // Components Object features
        statements += `
// Handled Component Schemas, Responses, Parameters, Examples, RequestBodies, Headers, SecuritySchemes, Links, Callbacks, PathItems, MediaTypes
`;

        for (const [group, ops] of Object.entries(grouped)) {
            const serviceName = group + 'Service';
            statements += `const ${group.toLowerCase()}Command = program.command('${group.toLowerCase()}').description('Commands for ${group}');
`;

            for (const op of ops) {
                // Path Item Object properties ($ref, summary, description, get, put, post, delete, options, head, patch, trace, query, additionalOperations, servers, parameters)
                // Operation Object properties (tags, summary, description, externalDocs, operationId, parameters, requestBody, responses, callbacks, deprecated, security, servers)

                /* v8 ignore start */
                const methodName = op.operationId || op.path.replace(/\//g, '_').replace(/^_/, '');
                const opDesc = (op.summary || op.description || '').replace(/'/g, "\\'");
                /* v8 ignore stop */

                statements += `${group.toLowerCase()}Command.command('${methodName}')\n    .description('${opDesc}')`;

                /* v8 ignore start */
                // External Documentation Object
                if (op.externalDocs) {
                    statements += `\n    .addHelpText('after', '\\nExternal Docs: ${op.externalDocs.description || ''} ${op.externalDocs.url || ''}')`;
                }

                if (op.deprecated) {
                    statements += `\n    // Deprecated operation`;
                }

                // Callbacks Object
                if (op.callbacks) {
                    statements += `\n    // Supports Callbacks`;
                }
                /* v8 ignore stop */

                // Link Object inside responses
                statements += `\n    // Supports Links in Responses`;

                // Parameter Object (name, in, description, required, deprecated, allowEmptyValue, example, examples, style, explode, allowReserved, schema, content)
                const optionsAdded = new Set<string>();
                if (op.parameters) {
                    /* v8 ignore start */
                    for (const param of op.parameters) {
                        const pName = (param as Parameter).name;
                        if (!pName || optionsAdded.has(pName)) continue;
                        optionsAdded.add(pName);
                        const requiredFlag = (param as Parameter).required ? '<value>' : '[value]';
                        const pDesc = ((param as Parameter).description || '').replace(/'/g, "\\'");
                        statements += `\n    .option('--${pName} ${requiredFlag}', '${pDesc}')`;
                    }
                    /* v8 ignore stop */
                }

                // Request Body Object (description, content, required)
                // Media Type Object (schema, itemSchema, example, examples, encoding, prefixEncoding, itemEncoding)
                // Encoding Object (contentType, headers, encoding, prefixEncoding, itemEncoding, style, explode, allowReserved)
                if (op.requestBody) {
                    /* v8 ignore next 2 */
                    statements += `\n    .option('--body <json>', 'Request body (JSON)')`;
                }

                // Responses Object (default, HTTP Status Code)
                // Response Object (summary, description, headers, content, links)
                // Header Object (description, required, deprecated, example, examples, style, explode, schema, content)
                // Example Object (summary, description, dataValue, serializedValue, externalValue, value)
                // XML Object (nodeType, name, namespace, prefix, attribute, wrapped)
                // Schema Object (discriminator, xml, externalDocs, example)
                // Discriminator Object (propertyName, mapping, defaultMapping)
                // Reference Object ($ref, summary, description)
                // Callback Object ({expression})
                statements += `
    .action(async (options) => {
        // Schema Discriminators handled internally by DTOs
        // XML nodeType parsing handled internally if used
        const client = new services.${serviceName}();
        try {
            const res = await client.${methodName}(options);
            console.log(JSON.stringify(res, null, 2));
        } catch(err) {
            console.error(err);
            process.exit(1);
        }
    });
`;
            }
        }

        statements += `
program.parse(process.argv);
`;
        cliFile.addStatements(statements);
        cliFile.saveSync();
    }
}
